# SPDX-FileCopyrightText: 2025 Alexandru Mihai Buzduc <lalibuzduc@gmail.com>
# SPDX-FileCopyrightText: 2025 Universal Blue
#
# SPDX-License-Identifier: Apache-2.0

[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[[customizations.user]]
name = "bismuth"
password = "bismuth"
groups = ["wheel"]